sudo: false
arch:
   - amd64
   - ppc64le
language: node_js
addons:
  sauce_connect: true
cache:
  directories:
    - node_modules
node_js:
   - 0.10 # to be removed 2016-10-31
   - 0.12 # to be removed 2016-12-31
   - 4 # to be removed 2018-04-01
   - 6 # to be removed 2019-04-01
   - lts/* # safety net; don't remove
   - node # safety net; don't remove
before_install:
  - npm i -g npm@latest
script:
  - npm test
after_success:
  - 'travis-after-all && npm run semantic-release'
env:
  global:
    - "SAUCE_USERNAME=chaijs-get-func-name"
    # SAUCE_ACCESS_KEY
    - secure: "RJM+OkpkK2LH+d5/V17TyIEji0OlNsWHzgJNp/+BpuoxtM2csxju+qncgsfT04rDGAm7SGe9pHWn4C5RhhaLfpx29xD2ynI6pWHln7XApN3I0bUE5G6KI051KUOi/TJ1QPKcFS8jQCwsSEjog8QSd68Zb/VJeTg6ic3My/+iETKSppx2C5ENNNyvJLrOYrdRokTTAC9hgzLA2qKBJ9/qSiSbijGAKjdAkYuFBdrGxuJbl3II68WHHmNzLW4v8uEt9iDVl8wUgbjVz/GkhGyhS/FltPW0857daBOGnc6Jj/Jzr5pav1Qb/e0vuYifUMrEhsQuBIPkdZDk0t53MHUC7KcLhrEuu9SrOemNRsYSTiKmVDu673t7hVqmUDF11owfWdDXs5SEzrxHfORHZLHjfkXcv5QUgODyVIEYQhpz97hxWs8PErg49SDF0S1pLyWZrlqRSt3cNolrPPpIO8JLmSQ4Ed4zoVcO2W1JmZgAR1LuluZPbIDmwA+6oewgWuMhBWd90fNvfJX/iCYJi8tQudNQwRjoBldz7hIF6baGz21/PWw7j/wsk2T9lBfxxzt1XTDxfFecnJczOiYM9h2MsQv5EcuSEdlw/lyadzKofUNhmnAp0ESw+GpuP//lDOV4rb2KztTh4rZSrP6B9Yydo8MRWcUVeSDw9hVuJuCJb7A="
    # NPM_TOKEN (be62c4e44c67)
    - secure: "JRJ1oWVNruZSiUpQNZhn7hy+YO7CydmUK6SFa7QIFxkmFUyEZdxgCUeczPUtnOOvc60RHoS05i7YD7EO7iUfwkl6bqj47P7cc+cgabVGjhLVe4EziH1MohyGLsmndJyVKmdIdIwMSVEJHxgw/1BZBKR50akw62faEGMQPOChxYSotT9bLZQ6W6Zh3CzgIFMd+pnrFAIAydSVhlmDoiXzLtXCmF7j2I7Eil2DKbLTStBFRg8rdC0twOk644a6NNDhkAFrs8cb4y2s8ExYY+RnhOinQ5XOW4oT3uYF7yp+EOofoc46TqfkkX54OqvJ8mTVZrJG1MXs39HDi5vL3NOHvSi/g4cIEt98CkGyifX81Wz96hbrxjLzRGW7yJKLSYM/KTElOxVNkN0X2NQaopQogTKa7ufI04lIDhtEkqWhzhNPqPR/h7H9bHvDoeMZPbiH8lyx4khTP5uiCnjIrewsrY3eK2/uzNK4SdTUfBEz2RbLNwHPC9kem83Aag0vIH7Wephazl8E/44UW8oaY66k93XcJfBj0j3Ur8GBpW73b+UZpY71vohCKkjIInNTOUIpakWh9Xf8Cj1FSok5JPlBGgmyCTAbRE597DQ/aQ9ObBYHaIavvMvSu5N9E/TK/WgGdnFn943xtDNencHOyzMLgTj6HK8xsULnlsPTp+7MB0g="
    # GH_TOKEN
    - secure: "hv+Agq13LpeFuDv5Lt9UfHn0vQYOUfIiMUrhxevXkvVq+6dooQFaksptFmHmKyrdcbmxhGn8nbvgjvgs2sWRBMtmEaHbHTBcJh3Q/9mwZwMllytoqPju+rjxxPOplEIKEANBx53pMyLk8R4ykA9df58frSj+Otlw7uhf+aindFdsx7ZbBQfytqTTUIHod8eM52yTFg1iG/CFMdBLpwpcqdX9K6ipPy6aivuDbHgTKlK0Vj4HbWK5h+q9H0E2gvRLEpkinMPlny929HNOkr2L4WitSE+Z7064j8VQE2fwQPfB6fPlSDwdAbR+9fXwJ+5pSzvRifiJz4uDF5CygashL7pW7Li64+T3OtoQFANTILFX3roF8c+fMYks3k5EaZcLMwQbV6Xl0LEC0tauYKptH1pIHEKw9udKCoEwkNABn6Kr3G4vdUHFKIfKWYUH22Cf9DT9bqNLs2mpsuUwapTspTSMB62xkkuK/JTaK5gtGzsmatd8v5LiUH2/OqKcwvh+EkDX9t5be0oMKezHZt91Z39vRVXNr64aZa3K0Ts3SIffu1gqoz2nOiuNOKH1Ff8QLyAG2YCSGzdfHj1l/HPV2rXz17Ilokm0RTcltbJgkCHOBGZi2bvkQDtEUw6H+ktAJpWw9QMJxvB6n9Jo+ZY5JtrMViQAp8qS/tjbnC6vr0k="
